---
title: "Week 2 lab"
author: "Haojia Li"
format: 
  gfm: default
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, cache = F, comment = "")
options(knitr.kable.NA = "")
options(digits = 6)
```

```{r}
rar_sim <- function(
    N             = 228, # total number of patients to be allocated in the trial
    interim       = 40, # size of each interim analysis when RAR is used
    trt_effect    = rep(0.35, 4), # treatment effect
    alpha         = 0.35, # alpha for all the arms in beta distribution
    beta          = 0.65, # beta for all the arms in beta distribution
    K             = 1000, # number of draws in posterior distribution
    rar           = T, # logical flag of whether to use RAR (T) or equal allocation (F)
    delta         = ifelse(rar, 0.9892, 0.9912) # threshold to determine a successful trial
) {
  # function 1 - allocate participants
  # inputs: 
  #   1. n - total number of patients to be allocated
  #   2. alloc_prob - allocation probability
  # output:
  #   number of participants (nt) allocated to each arm in a vector
  allocation <- function(n, alloc_prob) {
    nt <- round(n*alloc_prob)
    # make sure the sum of allocated numbers equals to the input n
    if(sum(nt, na.rm = T) != n) nt[1] <- n - sum(nt[-1], na.rm = T)
    return(nt)
  }
  
  # function 2 - flip the coin and count the number of successes
  # inputs:
  #   1. nt - number of participants allocated to each arm in a vector
  #   2. pt - treatment effect for each arm
  # output:
  #   number of successes (sum_yt) in each arm
  rbinom_success <- function(nt, pt) {
    mapply(rbinom, nt, 1, pt, SIMPLIFY = F) |> sapply(sum)
  }
  
  # function 3 - draw 1000 times from the posterior distribution
  # inputs:
  #   1. cum_nt - cumulative number of participants allocated to each arm in a vector
  #   2. cum_sum_yt - cumulative number of successes in each arm
  # output:
  #   posterior probability in matrix with 1000 rows and 4 columns (post_mat)
  posterior_prob <- function(cum_nt, cum_sum_yt) {
    mapply(rbeta, K, alpha + cum_sum_yt, beta + cum_nt - cum_sum_yt)
  }
  
  # function 4 - calculate V0, V1, V2, and V3 and re-normalized to be the adaptive allocation prob
  # inputs:
  #   post_mat - posterior matrix
  #   nt - number of participants allocated to each arm in a vector
  # output:
  #   new allocation probability (alloc_prob), summing up to 1
  adapt_allocpr <- function(post_mat, nt) {
    vt <- sapply(2:4, \(i) mean(apply(post_mat, 1, which.max) == i))
    v0 <- min(c(sum(vt * (nt[-1]+1) / (nt[1]+1)), max(vt)))
    return(c(v0,vt)/sum(c(v0,vt)))
  }
  
  # function 5 - calculate the probability that each treatment arm is better than control
  # input:
  #   post_mat - posterior matrix
  # output:
  #   probability that each treatment arm is better than control in a vector (pt_lt_p0)
  prob_pt_lt_p0 <- function(post_mat) {
    sapply(2:4, \(i) mean(post_mat[,i] > post_mat[,1]))
  }
  
  # define result components
  res <- vector(mode = "list", length = 5)
  names(res) <- c(
    "Design",
    "Num. of patients allocated (nt)", "Num. of successes (sum_yt)", 
    "Pr(post_prob_t > post_prob_0)", "Conclusion"
  )
  res$`Num. of patients allocated (nt)` <- res$`Num. of successes (sum_yt)` <- matrix(ncol = 4, nrow = 0)
  
  alloc_prob <- rep(0.25,4) # initial allocation probability regardless of design
  while(sum(res$`Num. of patients allocated (nt)`) < N) {
    if(rar) n <- min(interim, N - sum(res$`Num. of patients allocated (nt)`)) 
    else n <- N
    # 1. simulate nt and save it to `Num. of patients allocated (nt)`
    nt <- allocation(n, alloc_prob)
    res$`Num. of patients allocated (nt)` <- rbind(res$`Num. of patients allocated (nt)`, nt)
    # 2. simulate sum_yt and save it to `Num. of successes (sum_yt)`
    sum_yt <- rbinom_success(nt, trt_effect)
    res$`Num. of successes (sum_yt)` <- rbind(res$`Num. of successes (sum_yt)`, sum_yt)
    # 3. simulate posterior probability matrix based on cum_nt and cum_sum_yt
    post_mat <- posterior_prob(colSums(res$`Num. of patients allocated (nt)`), colSums(res$`Num. of successes (sum_yt)`))
    
    # 4. if the allocation for the whole trial has not been completed, calculate the adaptive allocation probability
    if(sum(res$`Num. of patients allocated (nt)`) < N) alloc_prob <- adapt_allocpr(post_mat, nt)
    # 5. else, calculate the probability that each treatment arm is better than control
    else res$`Pr(post_prob_t > post_prob_0)` <- prob_pt_lt_p0(post_mat)
  }
  
  colnames(res$`Num. of patients allocated (nt)`) <- colnames(res$`Num. of successes (sum_yt)`) <- 
    c("Ctrl", "Arm1", "Arm2", "Arm3")
  rownames(res$`Num. of patients allocated (nt)`) <- rownames(res$`Num. of successes (sum_yt)`) <- 
    1:nrow(res$`Num. of patients allocated (nt)`)
  names(res$`Pr(post_prob_t > post_prob_0)`) <- c("Arm1", "Arm2", "Arm3")
  if(rar) {
    res$Design <- "Response-adaptive randomization (RAR)"
    res$`Num. of patients allocated (nt)` <- addmargins(res$`Num. of patients allocated (nt)`)
    res$`Num. of successes (sum_yt)` <- addmargins(res$`Num. of successes (sum_yt)`)
  } else {
    res$Design <- "Equal allocation"
    res$`Num. of patients allocated (nt)` <- addmargins(res$`Num. of patients allocated (nt)`, 2)
    res$`Num. of successes (sum_yt)` <- addmargins(res$`Num. of successes (sum_yt)`, 2)
  }
  res$Conclusion <- paste0(
    "Comparing to the threshold of ", delta, ", the trial is a ", 
    ifelse(max(res$`Pr(post_prob_t > post_prob_0)`) > delta, "success.", "failure.")
  )
  return(res)
}
```

```{r}
set.seed(7045)
# simulation result of equal allocation
rar_sim(rar = F)
# simulation result of RAR
rar_sim()
```

```{r}
# parallel calculation
library(parallel)
cl <- makeCluster(detectCores() - 1)
clusterExport(cl, c("rar_sim"))

# replicate the design 10000 times
set.seed(7045)
# equal allocation
sim_equal <- parLapply(cl, 1:10000, function(i, ...) rar_sim(rar = F))
# RAR
sim_rar <- parLapply(cl, 1:10000, function(i, ...) rar_sim(rar = T))

# stop clustering
stopCluster(cl)

# generate the largest prob that one arm has a higher posterior rate than control
max_pt_lt_p0_equal <- sapply(sim_equal, \(x) max(x$`Pr(post_prob_t > post_prob_0)`))
max_pt_lt_p0_rar <- sapply(sim_rar, \(x) max(x$`Pr(post_prob_t > post_prob_0)`))

# depict the distribution
par(mfrow = c(1,2))
hist(max_pt_lt_p0_equal, main = "Equal allocation", xlab = "")
hist(max_pt_lt_p0_rar, main = "RAR", xlab = "")

# calculate the Type I error
mean(max_pt_lt_p0_equal >= 0.9912)
mean(max_pt_lt_p0_rar >= 0.9892)

# find threshold
quantile(max_pt_lt_p0_equal, 0.975)
quantile(max_pt_lt_p0_rar, 0.975)

# replicate the study design assuming treatment effect is 0.35, 0.35, 0.35 and 0.65 for the arms, respectively
rar_sim(trt_effect = c(0.35, 0.35, 0.35, 0.65), rar = F)
rar_sim(trt_effect = c(0.35, 0.35, 0.35, 0.65))
```
